# Generated by Django 6.0.7 on 2026-07-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_amount', models.IntegerField(default=5000)),
                ('penalty_rate', models.IntegerField(default=3)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_payout_amount', models.IntegerField(default=0)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.circle')),
                ('payout_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='circles.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('penalty', models.IntegerField(default=0)),
                ('is_late', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.membership')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.round')),
            ],
            options={
                'unique_together': {('round', 'member')},
            },
        ),
    ]
