# Generated by Django 6.0.7 on 2026-07-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_round_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='has_been_paid',
            field=models.BooleanField(default=False),
        ),
    ]
